### PR TITLE
Indicators Refactor (Do not merge)

### PR DESCRIPTION
**Pull request by eugene-eeo**
**Todo:**

 - [ ] Look into ways which `.update` is used
 - [ ] Clean up code
 - [ ] Separate math and UI code
 - [ ] Find/write tests for math code

### CODE REVIEW

**Comment by eugene-eeo** [comment]
@aminroosta when will `indicator.update` be called? If `.update` is not needed then we can greatly simplify the code. Currently the code needs to cover a lot of edge cases and IMHO this is not the way forward. Ideally we want to have something like:

```js
import 'mathFunction' from 'src/math/fn.js'

window.indicator = makeIndicator("id", mathFunction);
```

But I fully understand if for efficiency reasons we can't make it that simple.

**Comment by aminroosta** [comment]
@eugene-eeo 

> If .update is not needed then we can greatly simplify the code.

When chart is showing `ohlc` data (dutation  != tick) the `update` function gets called for the last ohlc bar.

> if for efficiency reasons we can't make it that simple ...

Exactly ... we need to keep minimal computation-order for each indicator (`O(N)` for simple indicators), That being said, we never really profiled indicators ... a functional approach like the one you suggested **might** even perform better.

**Comment by eugene-eeo** [comment]
## New Indicators API

```js
window.indicator = makeIndicator('id', function(indicator) {
    // ...
    return {
        update: tick => [time, value],
        next: tick => [time, value],
    };
});
```

 - `makeIndicator` returns a new subclass of `IndicatorBase`
 - specific functions like special `toString`/`getIDs` methods can be implemented:

```js
window.indicator = makeIndicator(/* ... */);

indicator.prototype.toString = function() {
    return /* ... */;
};
```

**Comment by aminroosta** [comment]
@eugene-eeo This is really good, Almost perfect ( ͡° ͜ʖ ͡°)

Just some final touches ...

1- Some indicators like `aroon`, `ao`, `bop`, `stddev`, `alligator`, `cks`, `dc` ... have a custom implementation of `buildSeriesAndAxisConfFromData()` function,  and their `update()` and `addPoint()` functions deal with multiple series. There are about 10 indicators like that.

2- I'd like to stop polluting the window namespace with `window.INDICATOR` assignments.
And also build indicators on demand ... Something like this:
```js
// File CC.js
export default (ind) => {
  // implementation ...
  return {
    update: /* ... */
    next: /* .... */
  }
};

// File ??? (maybe indicatorBase)
import cc from `./impl/cc.js`;
const Store = { };
export buildIndicator = (id) => {
  if (Store[id]) 
     return Store[id];
  Store[id] = makeIndicator(id, cc);
  return Store[id];
}
```

3- in `makeIndicator(id, F)` please don't pass `this` to  `F(this)` function, I mean if we can avoid touching the class instance in `F` function it's much better.

**Comment by eugene-eeo** [comment]
@aminroosta on point 3 I have tried to reduce the dependency on the indicator instance; one option is to pass the arguments given to the indicator constructor directly to the function:

```js
const klass = function(priceData, options, indicators) {
    IndicatorBase.call(this, priceData, options, indicators);
    this._f = F(priceData, options, indicators);
    this.priceData = priceData;
    priceData.forEach(x => this.addPoint(x));
}; 
```

But there are some indicators like ROC or WMA that need the indicator instance to get the `priceData` array. One option is to store each price datum in an array managed by `F()`:

```js
makeIndicator('id', function(data, options, indicator) {
    return {
        next: x => {
            data.push(x);
            return [x.time, x.close];
        }
    };
});
```

Which requires some repetition for each indicator; but I'll give it a try and see if I like it or not.

Point 2: Yeah I really agree with this one; feels very strange for me since we are using the `window` as a huge hash table while we should actually be using the `buildIndicator` function. What about this suggestion:

```js
// indicator_store.js
export registry = {};
```

```js
// indicators/max.js
registry.max = function(indicator) {
    // ...
    return {next, update};
};
```

**Comment by aminroosta** [comment]
@eugene-eeo Both of your approaches for points 2 & 3 looks good to me 👍

**Pull request closed without merging**
