### PR TITLE
Indicator

### PR DESCRIPTION
**Pull request by 4p00rv**
Please don't merge. Waiting for more issues.

### CODE REVIEW

**Comment by 4p00rv** [comment]
@aminroosta @arnabk You can merge this now.

**Comment by aminroosta** [comment]
@4p00rv please send the PR for the `dev` branch.

**Comment by ashkanx** [comment]
@aminroosta I changed the base branch to `dev`

**Comment by 4p00rv** [comment]
@aminroosta PR has been changed to dev already.

**Pull request merged**
